### ISSUE TITLE
Add a way to run experiments from protocol view

### ISSUE THREAD

**Issue by mirams** [ModellingWebLab/WebLab#104] opened 2019-01-15 15:46 UTC
In the old web lab we had a handy little 'Run experiments' button to the right of the protocol. But I can't see a way to do it in the new one without pressing all the buttons manually in the matrix?

(we also aren't showing the readme file at the moment, but that might be in another issue?)

**Screenshot from Travis:**
<kbd><img width="869" alt="image" src="https://user-images.githubusercontent.com/858776/51191417-3e621d80-18dc-11e9-82e5-3e9fb5ccf3a0.png"></kbd>

**Screenshot from Scrambler**
<kbd><img width="871" alt="image" src="https://user-images.githubusercontent.com/858776/51191375-25596c80-18dc-11e9-9ece-c01790205d55.png"></kbd>

**Comment by jonc125** [comment] 2019-01-15 16:12
Duplicate of #67.

Readmes are #75.

**Closed by jonc125** 2019-01-15 16:12 UTC
Labels: duplicate, enhancement
